response3 = \
    {'_links': {'self': {'href': 'https://api.edamam.com/api/recipes/v2/0f23ddc24c6f7889bda3347826884d9e/0f23ddc24c6f7889bda3347826884d9e?type=public&app_id=45bce103&app_key=b326299fbd784be300f3868ece1e9de8',
                     'title': 'Self'}},
 'recipe': {'calories': 6029.932759601088,
            'cautions': ['Gluten', 'Wheat', 'Sulfites'],
            'cuisineType': ['american'],
            'dietLabels': [],
            'digest': [{'daily': 640.0584636288461,
                        'hasRDI': True,
                        'label': 'Fat',
                        'schemaOrgTag': 'fatContent',
                        'sub': [{'daily': 512.90595525475,
                                 'hasRDI': True,
                                 'label': 'Saturated',
                                 'schemaOrgTag': 'saturatedFatContent',
                                 'tag': 'FASAT',
                                 'total': 102.58119105095,
                                 'unit': 'g'},
                                {'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Trans',
                                 'schemaOrgTag': 'transFatContent',
                                 'tag': 'FATRN',
                                 'total': 1.2384,
                                 'unit': 'g'},
                                {'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Monounsaturated',
                                 'schemaOrgTag': None,
                                 'tag': 'FAMS',
                                 'total': 197.5832316752,
                                 'unit': 'g'},
                                {'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Polyunsaturated',
                                 'schemaOrgTag': None,
                                 'tag': 'FAPU',
                                 'total': 79.295087919775,
                                 'unit': 'g'}],
                        'tag': 'FAT',
                        'total': 416.03800135874997,
                        'unit': 'g'},
                       {'daily': 63.424817128181736,
                        'hasRDI': True,
                        'label': 'Carbs',
                        'schemaOrgTag': 'carbohydrateContent',
                        'sub': [{'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Carbs (net)',
                                 'schemaOrgTag': None,
                                 'tag': 'CHOCDF.net',
                                 'total': 0.0,
                                 'unit': 'g'},
                                {'daily': 162.4908475300029,
                                 'hasRDI': True,
                                 'label': 'Fiber',
                                 'schemaOrgTag': 'fiberContent',
                                 'tag': 'FIBTG',
                                 'total': 40.622711882500724,
                                 'unit': 'g'},
                                {'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Sugars',
                                 'schemaOrgTag': 'sugarContent',
                                 'tag': 'SUGAR',
                                 'total': 114.50051748754419,
                                 'unit': 'g'},
                                {'daily': 0.0,
                                 'hasRDI': False,
                                 'label': 'Sugars, added',
                                 'schemaOrgTag': None,
                                 'tag': 'SUGAR.added',
                                 'total': 5.799725000294168,
                                 'unit': 'g'}],
                        'tag': 'CHOCDF',
                        'total': 190.27445138454522,
                        'unit': 'g'},
                       {'daily': 726.4879483105019,
                        'hasRDI': True,
                        'label': 'Protein',
                        'schemaOrgTag': 'proteinContent',
                        'tag': 'PROCNT',
                        'total': 363.243974155251,
                        'unit': 'g'},
                       {'daily': 639.84,
                        'hasRDI': True,
                        'label': 'Cholesterol',
                        'schemaOrgTag': 'cholesterolContent',
                        'tag': 'CHOLE',
                        'total': 1919.52,
                        'unit': 'mg'},
                       {'daily': 80.95848143125059,
                        'hasRDI': True,
                        'label': 'Sodium',
                        'schemaOrgTag': 'sodiumContent',
                        'tag': 'NA',
                        'total': 1943.0035543500144,
                        'unit': 'mg'},
                       {'daily': 85.26098338750218,
                        'hasRDI': True,
                        'label': 'Calcium',
                        'schemaOrgTag': None,
                        'tag': 'CA',
                        'total': 852.6098338750216,
                        'unit': 'mg'},
                       {'daily': 151.5629497023827,
                        'hasRDI': True,
                        'label': 'Magnesium',
                        'schemaOrgTag': None,
                        'tag': 'MG',
                        'total': 636.5643887500073,
                        'unit': 'mg'},
                       {'daily': 172.946823768621,
                        'hasRDI': True,
                        'label': 'Potassium',
                        'schemaOrgTag': None,
                        'tag': 'K',
                        'total': 8128.500717125187,
                        'unit': 'mg'},
                       {'daily': 148.87885747084167,
                        'hasRDI': True,
                        'label': 'Iron',
                        'schemaOrgTag': None,
                        'tag': 'FE',
                        'total': 26.7981943447515,
                        'unit': 'mg'},
                       {'daily': 310.19332304546174,
                        'hasRDI': True,
                        'label': 'Zinc',
                        'schemaOrgTag': None,
                        'tag': 'ZN',
                        'total': 34.121265535000795,
                        'unit': 'mg'},
                       {'daily': 544.9978292392879,
                        'hasRDI': True,
                        'label': 'Phosphorus',
                        'schemaOrgTag': None,
                        'tag': 'P',
                        'total': 3814.984804675015,
                        'unit': 'mg'},
                       {'daily': 84.61278471666668,
                        'hasRDI': True,
                        'label': 'Vitamin A',
                        'schemaOrgTag': None,
                        'tag': 'VITA_RAE',
                        'total': 761.5150624500001,
                        'unit': 'µg'},
                       {'daily': 197.10466760555758,
                        'hasRDI': True,
                        'label': 'Vitamin C',
                        'schemaOrgTag': None,
                        'tag': 'VITC',
                        'total': 177.39420084500182,
                        'unit': 'mg'},
                       {'daily': 552.3484336270833,
                        'hasRDI': True,
                        'label': 'Thiamin (B1)',
                        'schemaOrgTag': None,
                        'tag': 'THIA',
                        'total': 6.628181203524999,
                        'unit': 'mg'},
                       {'daily': 293.6585604557797,
                        'hasRDI': True,
                        'label': 'Riboflavin (B2)',
                        'schemaOrgTag': None,
                        'tag': 'RIBF',
                        'total': 3.817561285925136,
                        'unit': 'mg'},
                       {'daily': 682.9486865850027,
                        'hasRDI': True,
                        'label': 'Niacin (B3)',
                        'schemaOrgTag': None,
                        'tag': 'NIA',
                        'total': 109.27178985360044,
                        'unit': 'mg'},
                       {'daily': 682.8439128250066,
                        'hasRDI': True,
                        'label': 'Vitamin B6',
                        'schemaOrgTag': None,
                        'tag': 'VITB6A',
                        'total': 8.876970866725086,
                        'unit': 'mg'},
                       {'daily': 83.17657060000181,
                        'hasRDI': True,
                        'label': 'Folate equivalent (total)',
                        'schemaOrgTag': None,
                        'tag': 'FOLDFE',
                        'total': 332.70628240000724,
                        'unit': 'µg'},
                       {'daily': 0.0,
                        'hasRDI': False,
                        'label': 'Folate (food)',
                        'schemaOrgTag': None,
                        'tag': 'FOLFD',
                        'total': 332.70628240000724,
                        'unit': 'µg'},
                       {'daily': 0.0,
                        'hasRDI': False,
                        'label': 'Folic acid',
                        'schemaOrgTag': None,
                        'tag': 'FOLAC',
                        'total': 0.0,
                        'unit': 'µg'},
                       {'daily': 491.6000000000001,
                        'hasRDI': True,
                        'label': 'Vitamin B12',
                        'schemaOrgTag': None,
                        'tag': 'VITB12',
                        'total': 11.7984,
                        'unit': 'µg'},
                       {'daily': 13.76,
                        'hasRDI': True,
                        'label': 'Vitamin D',
                        'schemaOrgTag': None,
                        'tag': 'VITD',
                        'total': 2.064,
                        'unit': 'µg'},
                       {'daily': 142.50078778833333,
                        'hasRDI': True,
                        'label': 'Vitamin E',
                        'schemaOrgTag': None,
                        'tag': 'TOCPHA',
                        'total': 21.37511816825,
                        'unit': 'mg'},
                       {'daily': 113.76854311458335,
                        'hasRDI': True,
                        'label': 'Vitamin K',
                        'schemaOrgTag': None,
                        'tag': 'VITK1',
                        'total': 136.52225173750003,
                        'unit': 'µg'},
                       {'daily': 0.0,
                        'hasRDI': False,
                        'label': 'Sugar alcohols',
                        'schemaOrgTag': None,
                        'tag': 'Sugar.alcohol',
                        'total': 0.0,
                        'unit': 'g'},
                       {'daily': 0.0,
                        'hasRDI': False,
                        'label': 'Water',
                        'schemaOrgTag': None,
                        'tag': 'WATER',
                        'total': 3340.7214878203113,
                        'unit': 'g'}],
            'dishType': ['main course'],
            'healthLabels': ['Dairy-Free',
                             'Gluten-Free',
                             'Wheat-Free',
                             'Egg-Free',
                             'Peanut-Free',
                             'Tree-Nut-Free',
                             'Soy-Free',
                             'Fish-Free',
                             'Shellfish-Free',
                             'Pork-Free',
                             'Red-Meat-Free',
                             'Crustacean-Free',
                             'Celery-Free',
                             'Mustard-Free',
                             'Sesame-Free',
                             'Lupine-Free',
                             'Mollusk-Free',
                             'Kosher'],
            'image': 'https://edamam-product-images.s3.amazonaws.com/web-img/ae5/ae521a0e40b45c8cf64c143ad6a10ffd.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJIMEYCIQD0ql2T%2Fgsp1o3eTMmMYahSDyg1%2BZbjYiYU9IzZ%2BGDQCQIhANH%2FjV5EWQY2KkiRb%2FzLa6Rl6lpbeilKKSwuLMEuCYTKKtIECHYQABoMMTg3MDE3MTUwOTg2IgyUqULwVz4GrkkpV7kqrwSH3wBZyJESWgAhkxJP2fkQ7JuOKyrpc%2F%2Bz8s9XKVToIhA3tPkw8lEMvbF%2Fms%2BtT%2F6M4FHJRhgO3yTcNxpVb1C0E4Z2AXrevOuYDB2NxgdQfTS9%2BihTJk5fhtiYzXtk5uLmXBgnKTEM1o7alU53JT5nMFj0KyFiOI0xJkQvHkh633HM%2FwMXBNbRtX12Z89Tp%2FDp%2Fwjs9ikFgKcUdPFOj84PLanZwb0drf9VZLKxP0f5KN7yyg4IFO%2FUd9rbdBAeXu8acBXPclwYzeuJjvfR5i45%2Fo1sODYtmQy0aVepE6I7bnwnRC0E%2FELuzR8wLFfphU9LKlb5zDeE9pHqv8GFA4LwGjrJCriELf24zIV5Ypy3VBCfLonQ6ov4YJ5S6VHaZBWJfUpzDR%2FTvxv5BdwLFjW%2FIF1hh3I%2FR66vd9F6OwV4i3gGQnct98MK3Jdr6IbMlROjlALe31oBY%2BuvVupeXO38lZ5Y6JmXfx53ozj8%2BgBlukxiSuhbiYYFCPet0Tjud4UOpyLt%2BKFEpQdSwSj6RhoCmdQvDhXR24S1ZuYvg2bXJ7SxgIEedKsuzD0XEJEREfaOkiKh3ozmG1bWsCKtcoQOj6wqNzs8X2NfWDWlwSW0tT3fyNve%2FAdG%2F8zvyLb0bWeTjgvTo0W%2FdyBhq3ZIXGAKRKgvNj4zfGm0Zh10SNJCDe04PNj3roIkzlAhlh%2FQi07o4WGbvK96i6O6R4vKXMuNvVsYpOzBk4Kif0oDffTjMNCY2ZcGOqgBnkKCHiVoG1Z7O3Pm9W9nUyg%2BDbpentCVgLfPOP3su6l8pdLL7hi3ChXPVn2yxvYVi03BKIVVF9175SQqvo8nye9YErXOPGtOEEwM3AjFki%2BqTDFRaoNfoikzr%2FD2EE1VNj%2B6gaWyKZD5xDtcCyK9Yj7GbErBI1iQRP0PYuVU8VZZdTZaeQoRbgp3MA%2FiSa0osNue9zO3g1pIfAuM4iA3RgjV2KM9r86u&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220812T134004Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFCTNZUCWE%2F20220812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=74cdf226978416d3f9e9eaba8032c8d9cb416bd571131664748b35cd46c9f003',
            'images': {'REGULAR': {'height': 300,
                                   'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/ae5/ae521a0e40b45c8cf64c143ad6a10ffd.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJIMEYCIQD0ql2T%2Fgsp1o3eTMmMYahSDyg1%2BZbjYiYU9IzZ%2BGDQCQIhANH%2FjV5EWQY2KkiRb%2FzLa6Rl6lpbeilKKSwuLMEuCYTKKtIECHYQABoMMTg3MDE3MTUwOTg2IgyUqULwVz4GrkkpV7kqrwSH3wBZyJESWgAhkxJP2fkQ7JuOKyrpc%2F%2Bz8s9XKVToIhA3tPkw8lEMvbF%2Fms%2BtT%2F6M4FHJRhgO3yTcNxpVb1C0E4Z2AXrevOuYDB2NxgdQfTS9%2BihTJk5fhtiYzXtk5uLmXBgnKTEM1o7alU53JT5nMFj0KyFiOI0xJkQvHkh633HM%2FwMXBNbRtX12Z89Tp%2FDp%2Fwjs9ikFgKcUdPFOj84PLanZwb0drf9VZLKxP0f5KN7yyg4IFO%2FUd9rbdBAeXu8acBXPclwYzeuJjvfR5i45%2Fo1sODYtmQy0aVepE6I7bnwnRC0E%2FELuzR8wLFfphU9LKlb5zDeE9pHqv8GFA4LwGjrJCriELf24zIV5Ypy3VBCfLonQ6ov4YJ5S6VHaZBWJfUpzDR%2FTvxv5BdwLFjW%2FIF1hh3I%2FR66vd9F6OwV4i3gGQnct98MK3Jdr6IbMlROjlALe31oBY%2BuvVupeXO38lZ5Y6JmXfx53ozj8%2BgBlukxiSuhbiYYFCPet0Tjud4UOpyLt%2BKFEpQdSwSj6RhoCmdQvDhXR24S1ZuYvg2bXJ7SxgIEedKsuzD0XEJEREfaOkiKh3ozmG1bWsCKtcoQOj6wqNzs8X2NfWDWlwSW0tT3fyNve%2FAdG%2F8zvyLb0bWeTjgvTo0W%2FdyBhq3ZIXGAKRKgvNj4zfGm0Zh10SNJCDe04PNj3roIkzlAhlh%2FQi07o4WGbvK96i6O6R4vKXMuNvVsYpOzBk4Kif0oDffTjMNCY2ZcGOqgBnkKCHiVoG1Z7O3Pm9W9nUyg%2BDbpentCVgLfPOP3su6l8pdLL7hi3ChXPVn2yxvYVi03BKIVVF9175SQqvo8nye9YErXOPGtOEEwM3AjFki%2BqTDFRaoNfoikzr%2FD2EE1VNj%2B6gaWyKZD5xDtcCyK9Yj7GbErBI1iQRP0PYuVU8VZZdTZaeQoRbgp3MA%2FiSa0osNue9zO3g1pIfAuM4iA3RgjV2KM9r86u&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220812T134004Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFCTNZUCWE%2F20220812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=74cdf226978416d3f9e9eaba8032c8d9cb416bd571131664748b35cd46c9f003',
                                   'width': 300},
                       'SMALL': {'height': 200,
                                 'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/ae5/ae521a0e40b45c8cf64c143ad6a10ffd-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJIMEYCIQD0ql2T%2Fgsp1o3eTMmMYahSDyg1%2BZbjYiYU9IzZ%2BGDQCQIhANH%2FjV5EWQY2KkiRb%2FzLa6Rl6lpbeilKKSwuLMEuCYTKKtIECHYQABoMMTg3MDE3MTUwOTg2IgyUqULwVz4GrkkpV7kqrwSH3wBZyJESWgAhkxJP2fkQ7JuOKyrpc%2F%2Bz8s9XKVToIhA3tPkw8lEMvbF%2Fms%2BtT%2F6M4FHJRhgO3yTcNxpVb1C0E4Z2AXrevOuYDB2NxgdQfTS9%2BihTJk5fhtiYzXtk5uLmXBgnKTEM1o7alU53JT5nMFj0KyFiOI0xJkQvHkh633HM%2FwMXBNbRtX12Z89Tp%2FDp%2Fwjs9ikFgKcUdPFOj84PLanZwb0drf9VZLKxP0f5KN7yyg4IFO%2FUd9rbdBAeXu8acBXPclwYzeuJjvfR5i45%2Fo1sODYtmQy0aVepE6I7bnwnRC0E%2FELuzR8wLFfphU9LKlb5zDeE9pHqv8GFA4LwGjrJCriELf24zIV5Ypy3VBCfLonQ6ov4YJ5S6VHaZBWJfUpzDR%2FTvxv5BdwLFjW%2FIF1hh3I%2FR66vd9F6OwV4i3gGQnct98MK3Jdr6IbMlROjlALe31oBY%2BuvVupeXO38lZ5Y6JmXfx53ozj8%2BgBlukxiSuhbiYYFCPet0Tjud4UOpyLt%2BKFEpQdSwSj6RhoCmdQvDhXR24S1ZuYvg2bXJ7SxgIEedKsuzD0XEJEREfaOkiKh3ozmG1bWsCKtcoQOj6wqNzs8X2NfWDWlwSW0tT3fyNve%2FAdG%2F8zvyLb0bWeTjgvTo0W%2FdyBhq3ZIXGAKRKgvNj4zfGm0Zh10SNJCDe04PNj3roIkzlAhlh%2FQi07o4WGbvK96i6O6R4vKXMuNvVsYpOzBk4Kif0oDffTjMNCY2ZcGOqgBnkKCHiVoG1Z7O3Pm9W9nUyg%2BDbpentCVgLfPOP3su6l8pdLL7hi3ChXPVn2yxvYVi03BKIVVF9175SQqvo8nye9YErXOPGtOEEwM3AjFki%2BqTDFRaoNfoikzr%2FD2EE1VNj%2B6gaWyKZD5xDtcCyK9Yj7GbErBI1iQRP0PYuVU8VZZdTZaeQoRbgp3MA%2FiSa0osNue9zO3g1pIfAuM4iA3RgjV2KM9r86u&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220812T134004Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFCTNZUCWE%2F20220812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=877c72d645937e466aead7cbaedcbf24051a2a73d6dc168503c0c1b72a36d748',
                                 'width': 200},
                       'THUMBNAIL': {'height': 100,
                                     'url': 'https://edamam-product-images.s3.amazonaws.com/web-img/ae5/ae521a0e40b45c8cf64c143ad6a10ffd-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJIMEYCIQD0ql2T%2Fgsp1o3eTMmMYahSDyg1%2BZbjYiYU9IzZ%2BGDQCQIhANH%2FjV5EWQY2KkiRb%2FzLa6Rl6lpbeilKKSwuLMEuCYTKKtIECHYQABoMMTg3MDE3MTUwOTg2IgyUqULwVz4GrkkpV7kqrwSH3wBZyJESWgAhkxJP2fkQ7JuOKyrpc%2F%2Bz8s9XKVToIhA3tPkw8lEMvbF%2Fms%2BtT%2F6M4FHJRhgO3yTcNxpVb1C0E4Z2AXrevOuYDB2NxgdQfTS9%2BihTJk5fhtiYzXtk5uLmXBgnKTEM1o7alU53JT5nMFj0KyFiOI0xJkQvHkh633HM%2FwMXBNbRtX12Z89Tp%2FDp%2Fwjs9ikFgKcUdPFOj84PLanZwb0drf9VZLKxP0f5KN7yyg4IFO%2FUd9rbdBAeXu8acBXPclwYzeuJjvfR5i45%2Fo1sODYtmQy0aVepE6I7bnwnRC0E%2FELuzR8wLFfphU9LKlb5zDeE9pHqv8GFA4LwGjrJCriELf24zIV5Ypy3VBCfLonQ6ov4YJ5S6VHaZBWJfUpzDR%2FTvxv5BdwLFjW%2FIF1hh3I%2FR66vd9F6OwV4i3gGQnct98MK3Jdr6IbMlROjlALe31oBY%2BuvVupeXO38lZ5Y6JmXfx53ozj8%2BgBlukxiSuhbiYYFCPet0Tjud4UOpyLt%2BKFEpQdSwSj6RhoCmdQvDhXR24S1ZuYvg2bXJ7SxgIEedKsuzD0XEJEREfaOkiKh3ozmG1bWsCKtcoQOj6wqNzs8X2NfWDWlwSW0tT3fyNve%2FAdG%2F8zvyLb0bWeTjgvTo0W%2FdyBhq3ZIXGAKRKgvNj4zfGm0Zh10SNJCDe04PNj3roIkzlAhlh%2FQi07o4WGbvK96i6O6R4vKXMuNvVsYpOzBk4Kif0oDffTjMNCY2ZcGOqgBnkKCHiVoG1Z7O3Pm9W9nUyg%2BDbpentCVgLfPOP3su6l8pdLL7hi3ChXPVn2yxvYVi03BKIVVF9175SQqvo8nye9YErXOPGtOEEwM3AjFki%2BqTDFRaoNfoikzr%2FD2EE1VNj%2B6gaWyKZD5xDtcCyK9Yj7GbErBI1iQRP0PYuVU8VZZdTZaeQoRbgp3MA%2FiSa0osNue9zO3g1pIfAuM4iA3RgjV2KM9r86u&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220812T134004Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFCTNZUCWE%2F20220812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=85ff2e65d8ecae252699fd7fc10df07457057ea9e2070081cd7668e8351da4a9',
                                     'width': 100}},
            'ingredientLines': ['1/2 cup raisins or dried currants',
                                '3 tablespoons red wine vinegar',
                                '2 pounds small boiling onions',
                                '6 tablespoons extra-virgin olive oil',
                                '6 chicken leg-thigh pieces, cut apart',
                                '1 28-ounce can diced tomatoes in juice',
                                '1 cup canned low-salt chicken broth',
                                '1/2 cup dry white wine',
                                '1 tablespoon ground coriander',
                                '1 teaspoon honey',
                                '1 teaspoon ground allspice',
                                '1 teaspoon coarsely ground black pepper',
                                '2 bay leaves',
                                'Peel of 1 small orange, removed in strips '
                                'using vegetable peeler',
                                '1 cinnamon stick',
                                '1 teaspoon dried oregano'],
            'ingredients': [{'food': 'dried currants',
                             'foodCategory': 'fruit',
                             'foodId': 'food_avqayldaontvcna6fd2bxb2eryq6',
                             'image': 'https://www.edamam.com/food-img/b54/b5425d9ead1af7393c9e6dbe326d6391.jpg',
                             'measure': 'cup',
                             'quantity': 0.5,
                             'text': '1/2 cup raisins or dried currants',
                             'weight': 72.0},
                            {'food': 'red wine vinegar',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_ad6iyy1anmzb49a817rgnabnz8c9',
                             'image': 'https://www.edamam.com/food-img/dc8/dc8e998b32b8d45ba15c1b1e6711e958.jpg',
                             'measure': 'tablespoon',
                             'quantity': 3.0,
                             'text': '3 tablespoons red wine vinegar',
                             'weight': 44.7},
                            {'food': 'onions',
                             'foodCategory': 'vegetables',
                             'foodId': 'food_bmrvi4ob4binw9a5m7l07amlfcoy',
                             'image': 'https://www.edamam.com/food-img/205/205e6bf2399b85d34741892ef91cc603.jpg',
                             'measure': 'pound',
                             'quantity': 2.0,
                             'text': '2 pounds small boiling onions',
                             'weight': 907.18474},
                            {'food': 'extra-virgin olive oil',
                             'foodCategory': 'Oils',
                             'foodId': 'food_b1d1icuad3iktrbqby0hiagafaz7',
                             'image': 'https://www.edamam.com/food-img/4d6/4d651eaa8a353647746290c7a9b29d84.jpg',
                             'measure': 'tablespoon',
                             'quantity': 6.0,
                             'text': '6 tablespoons extra-virgin olive oil',
                             'weight': 81.0},
                            {'food': 'chicken leg',
                             'foodCategory': 'Poultry',
                             'foodId': 'food_ane1uw5amh8okda3qqu88bow58ul',
                             'image': 'https://www.edamam.com/food-img/f53/f53de7dd1054370cdfd98e18ccf77dbe.jpg',
                             'measure': '<unit>',
                             'quantity': 6.0,
                             'text': '6 chicken leg-thigh pieces, cut apart',
                             'weight': 2064.0},
                            {'food': 'can diced tomatoes',
                             'foodCategory': 'canned vegetables',
                             'foodId': 'food_a0edr25b8gjzxdbxcvus4blkd8b8',
                             'image': 'https://www.edamam.com/food-img/645/6455f54947348b60ec6557fcc0ef5121.jpeg',
                             'measure': 'ounce',
                             'quantity': 28.0,
                             'text': '1 28-ounce can diced tomatoes in juice',
                             'weight': 793.7866475000001},
                            {'food': 'low-salt chicken broth',
                             'foodCategory': 'canned soup',
                             'foodId': 'food_axg87lea13vni7a0lc9adauqgcs9',
                             'image': 'https://www.edamam.com/food-img/2eb/2eb3c708f58f5fa1543022650ff0ae8d.png',
                             'measure': 'cup',
                             'quantity': 1.0,
                             'text': '1 cup canned low-salt chicken broth',
                             'weight': 240.0},
                            {'food': 'dry white wine',
                             'foodCategory': 'wines',
                             'foodId': 'food_a656mk2a5dmqb2adiamu6beihduu',
                             'image': 'https://www.edamam.com/food-img/a71/a718cf3c52add522128929f1f324d2ab.jpg',
                             'measure': 'cup',
                             'quantity': 0.5,
                             'text': '1/2 cup dry white wine',
                             'weight': 117.6},
                            {'food': 'coriander',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_afpcy6rb44nx6gbfff63ga2cqksw',
                             'image': 'https://www.edamam.com/food-img/a90/a901cee0b9028841d258f5d07b5924e7.jpg',
                             'measure': 'tablespoon',
                             'quantity': 1.0,
                             'text': '1 tablespoon ground coriander',
                             'weight': 5.0},
                            {'food': 'honey',
                             'foodCategory': None,
                             'foodId': 'food_bn6aoj9atkqx8fbkli859bbbxx62',
                             'image': 'https://www.edamam.com/food-img/198/198c7b25c23b4235b4cc33818c7b335f.jpg',
                             'measure': 'teaspoon',
                             'quantity': 1.0,
                             'text': '1 teaspoon honey',
                             'weight': 7.0625000003582175},
                            {'food': 'ground allspice',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_avzem7oamop4dsa5wb65obt5ldgi',
                             'image': 'https://www.edamam.com/food-img/c3f/c3f96d47d334b92f0120ff0b3a512ec3.jpg',
                             'measure': 'teaspoon',
                             'quantity': 1.0,
                             'text': '1 teaspoon ground allspice',
                             'weight': 1.9},
                            {'food': 'black pepper',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_b6ywzluaaxv02wad7s1r9ag4py89',
                             'image': 'https://www.edamam.com/food-img/c6e/c6e5c3bd8d3bc15175d9766971a4d1b2.jpg',
                             'measure': 'teaspoon',
                             'quantity': 1.0,
                             'text': '1 teaspoon coarsely ground black pepper',
                             'weight': 2.3},
                            {'food': 'bay leaves',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_asx39x4ayja4jab6ivj6zayvkblo',
                             'image': 'https://www.edamam.com/food-img/0f9/0f9f5f95df173e9ffaaff2977bef88f3.jpg',
                             'measure': '<unit>',
                             'quantity': 2.0,
                             'text': '2 bay leaves',
                             'weight': 1.2},
                            {'food': 'orange',
                             'foodCategory': 'fruit',
                             'foodId': 'food_b0bnl8oayiqhs2at63ifxbm6i3o3',
                             'image': 'https://www.edamam.com/food-img/8ea/8ea264a802d6e643c1a340a77863c6ef.jpg',
                             'measure': 'peel',
                             'quantity': 1.0,
                             'text': 'Peel of 1 small orange, removed in '
                                     'strips using vegetable peeler',
                             'weight': 0.0},
                            {'food': 'cinnamon stick',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_atjxtznauw5zabaixm24xa787onz',
                             'image': 'https://www.edamam.com/food-img/d4d/d4daa18b92c596a1c99c08537c38e65b.jpg',
                             'measure': '<unit>',
                             'quantity': 1.0,
                             'text': '1 cinnamon stick',
                             'weight': 2.6},
                            {'food': 'dried oregano',
                             'foodCategory': 'Condiments and sauces',
                             'foodId': 'food_bkkw6v3bdf0sqiazmzyuiax7i8jr',
                             'image': 'https://www.edamam.com/food-img/1b0/1b0eaffb1c261606e0d82fed8e9747a7.jpg',
                             'measure': 'teaspoon',
                             'quantity': 1.0,
                             'text': '1 teaspoon dried oregano',
                             'weight': 1.0}],
            'label': 'Chicken, Onion, and Raisin Stew',
            'mealType': ['lunch/dinner'],
            'shareAs': 'http://www.edamam.com/recipe/chicken-onion-and-raisin-stew-0f23ddc24c6f7889bda3347826884d9e/-',
            'source': 'Epicurious',
            'totalDaily': {'CA': {'label': 'Calcium',
                                  'quantity': 85.26098338750218,
                                  'unit': '%'},
                           'CHOCDF': {'label': 'Carbs',
                                      'quantity': 63.424817128181736,
                                      'unit': '%'},
                           'CHOLE': {'label': 'Cholesterol',
                                     'quantity': 639.84,
                                     'unit': '%'},
                           'ENERC_KCAL': {'label': 'Energy',
                                          'quantity': 301.4966379800544,
                                          'unit': '%'},
                           'FASAT': {'label': 'Saturated',
                                     'quantity': 512.90595525475,
                                     'unit': '%'},
                           'FAT': {'label': 'Fat',
                                   'quantity': 640.0584636288461,
                                   'unit': '%'},
                           'FE': {'label': 'Iron',
                                  'quantity': 148.87885747084167,
                                  'unit': '%'},
                           'FIBTG': {'label': 'Fiber',
                                     'quantity': 162.4908475300029,
                                     'unit': '%'},
                           'FOLDFE': {'label': 'Folate equivalent (total)',
                                      'quantity': 83.17657060000181,
                                      'unit': '%'},
                           'K': {'label': 'Potassium',
                                 'quantity': 172.946823768621,
                                 'unit': '%'},
                           'MG': {'label': 'Magnesium',
                                  'quantity': 151.5629497023827,
                                  'unit': '%'},
                           'NA': {'label': 'Sodium',
                                  'quantity': 80.95848143125059,
                                  'unit': '%'},
                           'NIA': {'label': 'Niacin (B3)',
                                   'quantity': 682.9486865850027,
                                   'unit': '%'},
                           'P': {'label': 'Phosphorus',
                                 'quantity': 544.9978292392879,
                                 'unit': '%'},
                           'PROCNT': {'label': 'Protein',
                                      'quantity': 726.4879483105019,
                                      'unit': '%'},
                           'RIBF': {'label': 'Riboflavin (B2)',
                                    'quantity': 293.6585604557797,
                                    'unit': '%'},
                           'THIA': {'label': 'Thiamin (B1)',
                                    'quantity': 552.3484336270833,
                                    'unit': '%'},
                           'TOCPHA': {'label': 'Vitamin E',
                                      'quantity': 142.50078778833333,
                                      'unit': '%'},
                           'VITA_RAE': {'label': 'Vitamin A',
                                        'quantity': 84.61278471666668,
                                        'unit': '%'},
                           'VITB12': {'label': 'Vitamin B12',
                                      'quantity': 491.6000000000001,
                                      'unit': '%'},
                           'VITB6A': {'label': 'Vitamin B6',
                                      'quantity': 682.8439128250066,
                                      'unit': '%'},
                           'VITC': {'label': 'Vitamin C',
                                    'quantity': 197.10466760555758,
                                    'unit': '%'},
                           'VITD': {'label': 'Vitamin D',
                                    'quantity': 13.76,
                                    'unit': '%'},
                           'VITK1': {'label': 'Vitamin K',
                                     'quantity': 113.76854311458335,
                                     'unit': '%'},
                           'ZN': {'label': 'Zinc',
                                  'quantity': 310.19332304546174,
                                  'unit': '%'}},
            'totalNutrients': {'CA': {'label': 'Calcium',
                                      'quantity': 852.6098338750216,
                                      'unit': 'mg'},
                               'CHOCDF': {'label': 'Carbs',
                                          'quantity': 190.27445138454522,
                                          'unit': 'g'},
                               'CHOCDF.net': {'label': 'Carbohydrates (net)',
                                              'quantity': 0.0,
                                              'unit': 'g'},
                               'CHOLE': {'label': 'Cholesterol',
                                         'quantity': 1919.52,
                                         'unit': 'mg'},
                               'ENERC_KCAL': {'label': 'Energy',
                                              'quantity': 6029.932759601088,
                                              'unit': 'kcal'},
                               'FAMS': {'label': 'Monounsaturated',
                                        'quantity': 197.5832316752,
                                        'unit': 'g'},
                               'FAPU': {'label': 'Polyunsaturated',
                                        'quantity': 79.295087919775,
                                        'unit': 'g'},
                               'FASAT': {'label': 'Saturated',
                                         'quantity': 102.58119105095,
                                         'unit': 'g'},
                               'FAT': {'label': 'Fat',
                                       'quantity': 416.03800135874997,
                                       'unit': 'g'},
                               'FATRN': {'label': 'Trans',
                                         'quantity': 1.2384,
                                         'unit': 'g'},
                               'FE': {'label': 'Iron',
                                      'quantity': 26.7981943447515,
                                      'unit': 'mg'},
                               'FIBTG': {'label': 'Fiber',
                                         'quantity': 40.622711882500724,
                                         'unit': 'g'},
                               'FOLAC': {'label': 'Folic acid',
                                         'quantity': 0.0,
                                         'unit': 'µg'},
                               'FOLDFE': {'label': 'Folate equivalent (total)',
                                          'quantity': 332.70628240000724,
                                          'unit': 'µg'},
                               'FOLFD': {'label': 'Folate (food)',
                                         'quantity': 332.70628240000724,
                                         'unit': 'µg'},
                               'K': {'label': 'Potassium',
                                     'quantity': 8128.500717125187,
                                     'unit': 'mg'},
                               'MG': {'label': 'Magnesium',
                                      'quantity': 636.5643887500073,
                                      'unit': 'mg'},
                               'NA': {'label': 'Sodium',
                                      'quantity': 1943.0035543500144,
                                      'unit': 'mg'},
                               'NIA': {'label': 'Niacin (B3)',
                                       'quantity': 109.27178985360044,
                                       'unit': 'mg'},
                               'P': {'label': 'Phosphorus',
                                     'quantity': 3814.984804675015,
                                     'unit': 'mg'},
                               'PROCNT': {'label': 'Protein',
                                          'quantity': 363.243974155251,
                                          'unit': 'g'},
                               'RIBF': {'label': 'Riboflavin (B2)',
                                        'quantity': 3.817561285925136,
                                        'unit': 'mg'},
                               'SUGAR': {'label': 'Sugars',
                                         'quantity': 114.50051748754419,
                                         'unit': 'g'},
                               'SUGAR.added': {'label': 'Sugars, added',
                                               'quantity': 5.799725000294168,
                                               'unit': 'g'},
                               'Sugar.alcohol': {'label': 'Sugar alcohol',
                                                 'quantity': 0.0,
                                                 'unit': 'g'},
                               'THIA': {'label': 'Thiamin (B1)',
                                        'quantity': 6.628181203524999,
                                        'unit': 'mg'},
                               'TOCPHA': {'label': 'Vitamin E',
                                          'quantity': 21.37511816825,
                                          'unit': 'mg'},
                               'VITA_RAE': {'label': 'Vitamin A',
                                            'quantity': 761.5150624500001,
                                            'unit': 'µg'},
                               'VITB12': {'label': 'Vitamin B12',
                                          'quantity': 11.7984,
                                          'unit': 'µg'},
                               'VITB6A': {'label': 'Vitamin B6',
                                          'quantity': 8.876970866725086,
                                          'unit': 'mg'},
                               'VITC': {'label': 'Vitamin C',
                                        'quantity': 177.39420084500182,
                                        'unit': 'mg'},
                               'VITD': {'label': 'Vitamin D',
                                        'quantity': 2.064,
                                        'unit': 'µg'},
                               'VITK1': {'label': 'Vitamin K',
                                         'quantity': 136.52225173750003,
                                         'unit': 'µg'},
                               'WATER': {'label': 'Water',
                                         'quantity': 3340.7214878203113,
                                         'unit': 'g'},
                               'ZN': {'label': 'Zinc',
                                      'quantity': 34.121265535000795,
                                      'unit': 'mg'}},
            'totalTime': 0.0,
            'totalWeight': 4341.333887500359,
            'uri': 'http://www.edamam.com/ontologies/edamam.owl#recipe_0f23ddc24c6f7889bda3347826884d9e',
            'url': 'https://www.epicurious.com/recipes/food/views/chicken-onion-and-raisin-stew-106484',
            'yield': 6.0}}

expected_compilation_of_response_3 = {'Calories': '6029kcal',
 'Carbs which Sugar': '114g',
 'Fibre': '40g',
 'Image URL': 'https://edamam-product-images.s3.amazonaws.com/web-img/ae5/ae521a0e40b45c8cf64c143ad6a10ffd-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEA0aCXVzLWVhc3QtMSJIMEYCIQD0ql2T%2Fgsp1o3eTMmMYahSDyg1%2BZbjYiYU9IzZ%2BGDQCQIhANH%2FjV5EWQY2KkiRb%2FzLa6Rl6lpbeilKKSwuLMEuCYTKKtIECHYQABoMMTg3MDE3MTUwOTg2IgyUqULwVz4GrkkpV7kqrwSH3wBZyJESWgAhkxJP2fkQ7JuOKyrpc%2F%2Bz8s9XKVToIhA3tPkw8lEMvbF%2Fms%2BtT%2F6M4FHJRhgO3yTcNxpVb1C0E4Z2AXrevOuYDB2NxgdQfTS9%2BihTJk5fhtiYzXtk5uLmXBgnKTEM1o7alU53JT5nMFj0KyFiOI0xJkQvHkh633HM%2FwMXBNbRtX12Z89Tp%2FDp%2Fwjs9ikFgKcUdPFOj84PLanZwb0drf9VZLKxP0f5KN7yyg4IFO%2FUd9rbdBAeXu8acBXPclwYzeuJjvfR5i45%2Fo1sODYtmQy0aVepE6I7bnwnRC0E%2FELuzR8wLFfphU9LKlb5zDeE9pHqv8GFA4LwGjrJCriELf24zIV5Ypy3VBCfLonQ6ov4YJ5S6VHaZBWJfUpzDR%2FTvxv5BdwLFjW%2FIF1hh3I%2FR66vd9F6OwV4i3gGQnct98MK3Jdr6IbMlROjlALe31oBY%2BuvVupeXO38lZ5Y6JmXfx53ozj8%2BgBlukxiSuhbiYYFCPet0Tjud4UOpyLt%2BKFEpQdSwSj6RhoCmdQvDhXR24S1ZuYvg2bXJ7SxgIEedKsuzD0XEJEREfaOkiKh3ozmG1bWsCKtcoQOj6wqNzs8X2NfWDWlwSW0tT3fyNve%2FAdG%2F8zvyLb0bWeTjgvTo0W%2FdyBhq3ZIXGAKRKgvNj4zfGm0Zh10SNJCDe04PNj3roIkzlAhlh%2FQi07o4WGbvK96i6O6R4vKXMuNvVsYpOzBk4Kif0oDffTjMNCY2ZcGOqgBnkKCHiVoG1Z7O3Pm9W9nUyg%2BDbpentCVgLfPOP3su6l8pdLL7hi3ChXPVn2yxvYVi03BKIVVF9175SQqvo8nye9YErXOPGtOEEwM3AjFki%2BqTDFRaoNfoikzr%2FD2EE1VNj%2B6gaWyKZD5xDtcCyK9Yj7GbErBI1iQRP0PYuVU8VZZdTZaeQoRbgp3MA%2FiSa0osNue9zO3g1pIfAuM4iA3RgjV2KM9r86u&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220812T134004Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFCTNZUCWE%2F20220812%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=877c72d645937e466aead7cbaedcbf24051a2a73d6dc168503c0c1b72a36d748',
 'Ingredients': ['1/2 cup raisins or dried currants',
                 '3 tablespoons red wine vinegar',
                 '2 pounds small boiling onions',
                 '6 tablespoons extra-virgin olive oil',
                 '6 chicken leg-thigh pieces, cut apart',
                 '1 28-ounce can diced tomatoes in juice',
                 '1 cup canned low-salt chicken broth',
                 '1/2 cup dry white wine',
                 '1 tablespoon ground coriander',
                 '1 teaspoon honey',
                 '1 teaspoon ground allspice',
                 '1 teaspoon coarsely ground black pepper',
                 '2 bay leaves',
                 'Peel of 1 small orange, removed in strips using vegetable '
                 'peeler',
                 '1 cinnamon stick',
                 '1 teaspoon dried oregano'],
 'Mono Fat': '197g',
 'Name': 'Chicken, Onion, and Raisin Stew',
 'Net Carbs': '0g',
 'Poly Fat': '79g',
 'Protein': '363g',
 'Recipe ID': '0f23ddc24c6f7889bda3347826884d9e',
 'Recipe URL': 'https://www.epicurious.com/recipes/food/views/chicken-onion-and-raisin-stew-106484',
 'Salt': '1943mg',
 'Sat Fat': '102g',
 'Source': 'Epicurious',
 'Total Carbs': '190g',
 'Total Fat': '416g'}